### get all messages
GET http://localhost:8082/messages
Accept: application/json

### insert invalid message, invalid date
POST http://localhost:8082/messages
Content-Type: application/json

{
  "dateSent": "invalid",
  "type": "CSV_LINE",
  "sender": "0712345678",
  "receiver": "0723456789",
  "content": "Test 1 with everything"
}

### insert valid message
POST http://localhost:8082/messages
Content-Type: application/json

{
  "dateSent": "2024-01-06T19:47:42.138+00:00",
  "type": "SMS",
  "sender": "0734567890",
  "receiver": "0745678901",
  "content": "Test 2 with everything"
}

### bulk insert valid messages
POST http://localhost:8082/messages/bulk
Content-Type: application/json

[
  {
    "dateSent": "2024-01-06T19:47:42.138+00:00",
    "type": "SMS",
    "sender": "0734567890",
    "receiver": "0745678901",
    "content": "Test 2 with everything"
  },
  {
    "dateSent": "2024-01-07T20:47:42.138+00:00",
    "type": "CSV_LINE",
    "sender": "0756789012",
    "receiver": "0767890123",
    "content": "Test 3 with everything"
  },
  {
    "dateSent": "2024-01-08T21:47:42.138+00:00",
    "type": "SMS",
    "sender": "0778901234",
    "receiver": "0789012345",
    "content": "Test 4 with everything"
  },
  {
    "dateSent": "2024-01-09T22:47:42.138+00:00",
    "type": "CSV_LINE",
    "sender": "0790123456",
    "receiver": "0801234567",
    "content": "Test 5 with everything"
  },
  {
    "dateSent": "2024-01-10T23:47:42.138+00:00",
    "type": "SMS",
    "sender": "0812345678",
    "receiver": "0823456789",
    "content": "Test 6 with everything"
  },
  {
    "dateSent": "2024-01-11T00:47:42.138+00:00",
    "type": "CSV_LINE",
    "sender": "0834567890",
    "receiver": "0845678901",
    "content": "Test 7 with everything"
  },
  {
    "dateSent": "2024-01-12T01:47:42.138+00:00",
    "type": "SMS",
    "sender": "0856789012",
    "receiver": "0867890123",
    "content": "Test 8 with everything"
  },
  {
    "dateSent": "2024-01-13T02:47:42.138+00:00",
    "type": "CSV_LINE",
    "sender": "0878901234",
    "receiver": "0889012345",
    "content": "Test 9 with everything"
  },
  {
    "dateSent": "2024-01-14T03:47:42.138+00:00",
    "type": "SMS",
    "sender": "0890123456",
    "receiver": "0901234567",
    "content": "Test 10 with everything"
  }
]

### insert valid message
POST http://localhost:8082/messages
Content-Type: application/json

{
  "dateSent": "2024-01-01",
  "type": "SMS",
  "sender": "0734567890",
  "receiver": "0745678901",
  "content": "Test 2 with everything"
}

### get all messages
GET http://localhost:8082/messages?delta=2024-03-18T19:47:42.138%2B00:00&page=2&size=2
Accept: application/json


